channels:
- conda-forge
dependencies:
- python=3.9.18
- pip<=23.3.1
- pip:
  - mlflow
  - boto3==1.26.8
  - cloudpickle==2.2.1
  - fsspec==2023.12.2
  - google-api-python-client==2.111.0
  - google-cloud-storage==2.13.0
  - pillow==10.1.0
  - scikit-learn==1.3.2
  - tensorflow-macos==2.15.0
name: mlflow-env
