channels:
- conda-forge
dependencies:
- python=3.9.18
- pip<=23.3.1
- pip:
  - mlflow
  - cloudpickle==2.2.1
  - lightgbm==4.2.0
  - matplotlib==3.8.1
  - psutil==5.9.6
  - pyarrow==14.0.0
  - scikit-learn==1.3.2
name: mlflow-env
