channels:
- conda-forge
dependencies:
- python=3.9.18
- pip<=23.3.1
- pip:
  - mlflow==2.9.2
  - boto3==1.34.14
  - cloudpickle==3.0.0
  - fsspec==2023.12.2
  - google-api-python-client==2.111.0
  - google-cloud-storage==2.13.0
  - numpy==1.26.1
  - packaging==23.2
  - pandas==2.1.3
  - protobuf==4.23.4
  - pyyaml==6.0.1
  - requests==2.31.0
  - scikit-learn==1.3.2
  - scipy==1.11.3
  - tensorflow-macos==2.15.0
name: mlflow-env
